@server-name = http://localhost:29318
@base-path = /rest-api

GET {{server-name}}{{base-path}}

###
POST {{server-name}}{{base-path}}/api?stage=dev&hostname=apimanager.com
#Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="configFile"; filename="minimal-config.json"
Content-Type: application/json

< ./minimal-config.json
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="apiDefinition"; filename="petstore.json"
Content-Type: application/json

< ./petstore.json
------WebKitFormBoundary7MA4YWxkTrZu0gW--